---@class Sallo.Param.Rank
local a = {
    ["Bronze"] = {
        ["mxp_gauge"] = 872,
        ["mxp_total"] = 872,
        ["rank_level"] = 1,
        ["rank_name"] = "Bronze",
        ["skill_pt"] = nil,
    },
    ["Silver"] = {
        ["mxp_gauge"] = 3136,
        ["mxp_total"] = 4008,
        ["rank_level"] = 2,
        ["rank_name"] = "Silver",
        ["skill_pt"] = nil,
    },
    ["Gold"] = {
        ["mxp_gauge"] = 5772,
        ["mxp_total"] = 9780,
        ["rank_level"] = 3,
        ["rank_name"] = "Gold",
        ["skill_pt"] = nil,
    },
    ["Platinum"] = {
        ["mxp_gauge"] = 8636,
        ["mxp_total"] = 18416,
        ["rank_level"] = 4,
        ["rank_name"] = "Platinum",
        ["skill_pt"] = nil,
    },
    ["Diamond"] = {
        ["mxp_gauge"] = 11672,
        ["mxp_total"] = 30088,
        ["rank_level"] = 5,
        ["rank_name"] = "Diamond",
        ["skill_pt"] = nil,
    },
    ["Master"] = {
        ["mxp_gauge"] = 14848,
        ["mxp_total"] = 44936,
        ["rank_level"] = 6,
        ["rank_name"] = "Master",
        ["skill_pt"] = nil,
    },
    ["GrandMaster"] = {
        ["mxp_gauge"] = 18142,
        ["mxp_total"] = 63078,
        ["rank_level"] = 7,
        ["rank_name"] = "GrandMaster",
        ["skill_pt"] = nil,
    },
    ["Challenger"] = {
        ["mxp_gauge"] = 21540,
        ["mxp_total"] = 84618,
        ["rank_level"] = 8,
        ["rank_name"] = "Challenger",
        ["skill_pt"] = nil,
    },
    ["MasterChallenger"] = {
        ["mxp_gauge"] = 25029,
        ["mxp_total"] = 109647,
        ["rank_level"] = 9,
        ["rank_name"] = "MasterChallenger",
        ["skill_pt"] = nil,
    },
    ["Selendis"] = {
        ["mxp_gauge"] = 28602,
        ["mxp_total"] = 138249,
        ["rank_level"] = 10,
        ["rank_name"] = "Selendis",
        ["skill_pt"] = nil,
    },
    ["Honor"] = {
        ["mxp_gauge"] = 32252,
        ["mxp_total"] = 170501,
        ["rank_level"] = 11,
        ["rank_name"] = "Honor",
        ["skill_pt"] = nil,
    },
    ["Rage"] = {
        ["mxp_gauge"] = 35971,
        ["mxp_total"] = 206472,
        ["rank_level"] = 12,
        ["rank_name"] = "Rage",
        ["skill_pt"] = nil,
    },
    ["Bahar"] = {
        ["mxp_gauge"] = 39756,
        ["mxp_total"] = 246228,
        ["rank_level"] = 13,
        ["rank_name"] = "Bahar",
        ["skill_pt"] = nil,
    },
    ["Arcane"] = {
        ["mxp_gauge"] = 43602,
        ["mxp_total"] = 289830,
        ["rank_level"] = 14,
        ["rank_name"] = "Arcane",
        ["skill_pt"] = nil,
    },
    ["BlueHole"] = {
        ["mxp_gauge"] = 47506,
        ["mxp_total"] = 337336,
        ["rank_level"] = 15,
        ["rank_name"] = "BlueHole",
        ["skill_pt"] = nil,
    },
    ["Skull"] = {
        ["mxp_gauge"] = 51464,
        ["mxp_total"] = 388800,
        ["rank_level"] = 16,
        ["rank_name"] = "Skull",
        ["skill_pt"] = nil,
    },
}
return a
